# DO NOT MODIFY. This was automatically generated by sbt-bazel.
rules_scala_version = '8359fc6781cf3102e918c84cb1638a1b1e050ce0'
http_archive(
  name = 'io_bazel_rules_scala',
  url = 'https://github.com/bazelbuild/rules_scala/archive/%s.zip' % rules_scala_version,
  type = 'zip',
  strip_prefix = 'rules_scala-%s' % rules_scala_version
)
load(
  '@io_bazel_rules_scala//scala:scala.bzl',
  'scala_repositories'
)
scala_repositories()
load(
  '@io_bazel_rules_scala//scala:toolchains.bzl',
  'scala_register_toolchains'
)
scala_register_toolchains()
load(
  '@io_bazel_rules_scala//scala:scala_maven_import_external.bzl',
  'scala_maven_import_external'
)
scala_maven_import_external(
  name = 'com_chuusai_shapeless_2_12',
  artifact = 'com.chuusai:shapeless_2.12:2.3.3',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/com/chuusai/shapeless_2_12',
  actual = '@com_chuusai_shapeless_2_12//jar'
)
scala_maven_import_external(
  name = 'com_cibo_evilplot_2_12',
  artifact = 'com.cibo:evilplot_2.12:0.6.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/com/cibo/evilplot_2_12',
  actual = '@com_cibo_evilplot_2_12//jar'
)
scala_maven_import_external(
  name = 'com_google_code_findbugs_jsr305',
  artifact = 'com.google.code.findbugs:jsr305:3.0.1',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/com/google/code/findbugs/jsr305',
  actual = '@com_google_code_findbugs_jsr305//jar'
)
scala_maven_import_external(
  name = 'com_google_flogger_flogger',
  artifact = 'com.google.flogger:flogger:0.3.1',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/com/google/flogger/flogger',
  actual = '@com_google_flogger_flogger//jar'
)
scala_maven_import_external(
  name = 'com_google_flogger_flogger_system_backend',
  artifact = 'com.google.flogger:flogger-system-backend:0.3.1',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/com/google/flogger/flogger_system_backend',
  actual = '@com_google_flogger_flogger_system_backend//jar'
)
scala_maven_import_external(
  name = 'com_stripe_rainier_shaded_asm_6_0',
  artifact = 'com.stripe:rainier-shaded-asm_6.0:0.2.1',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/com/stripe/rainier_shaded_asm_6_0',
  actual = '@com_stripe_rainier_shaded_asm_6_0//jar'
)
scala_maven_import_external(
  name = 'io_circe_circe_core_2_12',
  artifact = 'io.circe:circe-core_2.12:0.9.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/io/circe/circe_core_2_12',
  actual = '@io_circe_circe_core_2_12//jar'
)
scala_maven_import_external(
  name = 'io_circe_circe_generic_extras_2_12',
  artifact = 'io.circe:circe-generic-extras_2.12:0.9.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/io/circe/circe_generic_extras_2_12',
  actual = '@io_circe_circe_generic_extras_2_12//jar'
)
scala_maven_import_external(
  name = 'io_circe_circe_generic_2_12',
  artifact = 'io.circe:circe-generic_2.12:0.9.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/io/circe/circe_generic_2_12',
  actual = '@io_circe_circe_generic_2_12//jar'
)
scala_maven_import_external(
  name = 'io_circe_circe_jawn_2_12',
  artifact = 'io.circe:circe-jawn_2.12:0.9.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/io/circe/circe_jawn_2_12',
  actual = '@io_circe_circe_jawn_2_12//jar'
)
scala_maven_import_external(
  name = 'io_circe_circe_numbers_2_12',
  artifact = 'io.circe:circe-numbers_2.12:0.9.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/io/circe/circe_numbers_2_12',
  actual = '@io_circe_circe_numbers_2_12//jar'
)
scala_maven_import_external(
  name = 'io_circe_circe_parser_2_12',
  artifact = 'io.circe:circe-parser_2.12:0.9.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/io/circe/circe_parser_2_12',
  actual = '@io_circe_circe_parser_2_12//jar'
)
scala_maven_import_external(
  name = 'net_sf_jopt_simple_jopt_simple',
  artifact = 'net.sf.jopt-simple:jopt-simple:4.6',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/net/sf/jopt/simple/jopt_simple',
  actual = '@net_sf_jopt_simple_jopt_simple//jar'
)
scala_maven_import_external(
  name = 'org_apache_commons_commons_math3',
  artifact = 'org.apache.commons:commons-math3:3.2',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/apache/commons/commons_math3',
  actual = '@org_apache_commons_commons_math3//jar'
)
scala_maven_import_external(
  name = 'org_openjdk_jmh_jmh_core',
  artifact = 'org.openjdk.jmh:jmh-core:1.21',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/openjdk/jmh/jmh_core',
  actual = '@org_openjdk_jmh_jmh_core//jar'
)
scala_maven_import_external(
  name = 'org_openjdk_jmh_jmh_generator_asm',
  artifact = 'org.openjdk.jmh:jmh-generator-asm:1.21',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/openjdk/jmh/jmh_generator_asm',
  actual = '@org_openjdk_jmh_jmh_generator_asm//jar'
)
scala_maven_import_external(
  name = 'org_openjdk_jmh_jmh_generator_bytecode',
  artifact = 'org.openjdk.jmh:jmh-generator-bytecode:1.21',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/openjdk/jmh/jmh_generator_bytecode',
  actual = '@org_openjdk_jmh_jmh_generator_bytecode//jar'
)
scala_maven_import_external(
  name = 'org_openjdk_jmh_jmh_generator_reflection',
  artifact = 'org.openjdk.jmh:jmh-generator-reflection:1.21',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/openjdk/jmh/jmh_generator_reflection',
  actual = '@org_openjdk_jmh_jmh_generator_reflection//jar'
)
scala_maven_import_external(
  name = 'org_ow2_asm_asm',
  artifact = 'org.ow2.asm:asm:5.0.3',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/ow2/asm/asm',
  actual = '@org_ow2_asm_asm//jar'
)
scala_maven_import_external(
  name = 'org_ow2_asm_asm',
  artifact = 'org.ow2.asm:asm:6.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/ow2/asm/asm',
  actual = '@org_ow2_asm_asm//jar'
)
scala_maven_import_external(
  name = 'org_ow2_asm_asm_tree',
  artifact = 'org.ow2.asm:asm-tree:6.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/ow2/asm/asm_tree',
  actual = '@org_ow2_asm_asm_tree//jar'
)
scala_maven_import_external(
  name = 'org_scala_lang_scala_reflect',
  artifact = 'org.scala-lang:scala-reflect:2.12.8',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/scala/lang/scala_reflect',
  actual = '@org_scala_lang_scala_reflect//jar'
)
scala_maven_import_external(
  name = 'org_scala_lang_modules_scala_xml_2_12',
  artifact = 'org.scala-lang.modules:scala-xml_2.12:1.0.6',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/scala/lang/modules/scala_xml_2_12',
  actual = '@org_scala_lang_modules_scala_xml_2_12//jar'
)
scala_maven_import_external(
  name = 'org_scala_sbt_test_interface',
  artifact = 'org.scala-sbt:test-interface:1.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/scala/sbt/test_interface',
  actual = '@org_scala_sbt_test_interface//jar'
)
scala_maven_import_external(
  name = 'org_scalacheck_scalacheck_2_12',
  artifact = 'org.scalacheck:scalacheck_2.12:1.14.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/scalacheck/scalacheck_2_12',
  actual = '@org_scalacheck_scalacheck_2_12//jar'
)
scala_maven_import_external(
  name = 'org_scalactic_scalactic_2_12',
  artifact = 'org.scalactic:scalactic_2.12:3.0.1',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/scalactic/scalactic_2_12',
  actual = '@org_scalactic_scalactic_2_12//jar'
)
scala_maven_import_external(
  name = 'org_scalactic_scalactic_2_12',
  artifact = 'org.scalactic:scalactic_2.12:3.0.5',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/scalactic/scalactic_2_12',
  actual = '@org_scalactic_scalactic_2_12//jar'
)
scala_maven_import_external(
  name = 'org_scalatest_scalatest_2_12',
  artifact = 'org.scalatest:scalatest_2.12:3.0.5',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/scalatest/scalatest_2_12',
  actual = '@org_scalatest_scalatest_2_12//jar'
)
scala_maven_import_external(
  name = 'org_spire_math_jawn_parser_2_12',
  artifact = 'org.spire-math:jawn-parser_2.12:0.11.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/spire/math/jawn_parser_2_12',
  actual = '@org_spire_math_jawn_parser_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_catalysts_macros_2_12',
  artifact = 'org.typelevel:catalysts-macros_2.12:0.0.5',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/catalysts_macros_2_12',
  actual = '@org_typelevel_catalysts_macros_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_catalysts_platform_2_12',
  artifact = 'org.typelevel:catalysts-platform_2.12:0.0.5',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/catalysts_platform_2_12',
  actual = '@org_typelevel_catalysts_platform_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_cats_core_2_12',
  artifact = 'org.typelevel:cats-core_2.12:1.0.1',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/cats_core_2_12',
  actual = '@org_typelevel_cats_core_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_cats_core_2_12',
  artifact = 'org.typelevel:cats-core_2.12:1.1.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/cats_core_2_12',
  actual = '@org_typelevel_cats_core_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_cats_kernel_laws_2_12',
  artifact = 'org.typelevel:cats-kernel-laws_2.12:1.1.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/cats_kernel_laws_2_12',
  actual = '@org_typelevel_cats_kernel_laws_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_cats_kernel_2_12',
  artifact = 'org.typelevel:cats-kernel_2.12:1.0.1',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/cats_kernel_2_12',
  actual = '@org_typelevel_cats_kernel_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_cats_kernel_2_12',
  artifact = 'org.typelevel:cats-kernel_2.12:1.1.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/cats_kernel_2_12',
  actual = '@org_typelevel_cats_kernel_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_cats_laws_2_12',
  artifact = 'org.typelevel:cats-laws_2.12:1.1.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/cats_laws_2_12',
  actual = '@org_typelevel_cats_laws_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_cats_macros_2_12',
  artifact = 'org.typelevel:cats-macros_2.12:1.0.1',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/cats_macros_2_12',
  actual = '@org_typelevel_cats_macros_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_cats_macros_2_12',
  artifact = 'org.typelevel:cats-macros_2.12:1.1.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/cats_macros_2_12',
  actual = '@org_typelevel_cats_macros_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_cats_testkit_2_12',
  artifact = 'org.typelevel:cats-testkit_2.12:1.1.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/cats_testkit_2_12',
  actual = '@org_typelevel_cats_testkit_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_discipline_2_12',
  artifact = 'org.typelevel:discipline_2.12:0.8',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/discipline_2_12',
  actual = '@org_typelevel_discipline_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_machinist_2_12',
  artifact = 'org.typelevel:machinist_2.12:0.6.2',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/machinist_2_12',
  actual = '@org_typelevel_machinist_2_12//jar'
)
scala_maven_import_external(
  name = 'org_typelevel_macro_compat_2_12',
  artifact = 'org.typelevel:macro-compat_2.12:1.1.1',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/org/typelevel/macro_compat_2_12',
  actual = '@org_typelevel_macro_compat_2_12//jar'
)
scala_maven_import_external(
  name = 'pl_project13_scala_sbt_jmh_extras',
  artifact = 'pl.project13.scala:sbt-jmh-extras:0.3.4',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/pl/project13/scala/sbt_jmh_extras',
  actual = '@pl_project13_scala_sbt_jmh_extras//jar'
)
scala_maven_import_external(
  name = 'sh_almond_interpreter_api_2_12',
  artifact = 'sh.almond:interpreter-api_2.12:0.3.0',
  licenses = [],
  server_urls = [
    'https://repo1.maven.org/maven2/',
    'http://dl.bintray.com/tpolecat/maven',
    'https://dl.bintray.com/cibotech/public/',
    'https://jitpack.io',
  ]
)
bind(
  name = 'jar/sh/almond/interpreter_api_2_12',
  actual = '@sh_almond_interpreter_api_2_12//jar'
)

git_repository(
    name = "com_github_johnynek_bazel_jar_jar",
    commit = "258c7288db8a034e087b4d65a52546830633a4f1",
    remote = "git://github.com/johnynek/bazel_jar_jar.git",
)
load(
    "@com_github_johnynek_bazel_jar_jar//:jar_jar.bzl",
    "jar_jar_repositories",
)
jar_jar_repositories()
