name: CI
on:
  pull_request:
env:
  SCALAC_FATAL_WARNINGS: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: scalafmt
        run: sbt scalafmtCheck
      - name: test
        run: sbt '+test'
      - name: docs
        run: sbt 'docs/mdoc'
