name: Publish
on:
  push:
    tags:
      - v*
env:
  SCALAC_FATAL_WARNINGS: true
  BINTRAY_USER: ${{ secrets.bintrayuser }}
  BINTRAY_PASS: ${{ secrets.bintraypass }}
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
      - uses: olafurpg/setup-scala@49fc8c734ef6916b4e1da8ba8d81bb26a2b46a06 # v7
      - run: sbt publish
